using System;
using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;

namespace CompleteTinyFont
{
    /// <summary>
    /// Replaces CK's reduced <c>thinTiny</c> face (atlas <c>rrs5</c>, 114
    /// codepoints, no accents) with the mod's full 331-glyph build.
    ///
    /// <para>Mechanism: <c>thinTiny</c> ships its own <c>_customCharset</c>
    /// starting at ASCII 33, while <c>thinSmall</c> uses the shared static
    /// <c>PugFont.latinCharset</c> — exactly 384 characters, one per atlas cell.
    /// The master atlas is drawn in that same order, so clearing
    /// <c>_customCharset</c> and rebuilding <c>glyphData</c> per cell index makes
    /// charset position, glyph index and atlas cell one coordinate. CK's own
    /// <c>PugFont.InitCodePoints()</c> then builds <c>codePoints</c> and the glyph
    /// sprites with its own convention (outline-padded rect, centered pivot), so
    /// this mod does not replicate it.</para>
    ///
    /// <para><c>charDims</c> deliberately stays at (8, 10): it is layout metric
    /// only (line advance, reported text dimensions), not atlas geometry. Raising
    /// it to the atlas's 12 px cell height would grow every line gap in existing
    /// mod UIs by 2 px.</para>
    ///
    /// <para>The rect passed to <c>InitCodePoints()</c> is one row taller than the
    /// drawn glyph (<c>RectH</c> = <c>BoxH</c> + 2, not <c>BoxH</c>): CK derives
    /// every sprite from <c>rect2 = (rect.y + 1, rect.height - 1)</c>, discarding
    /// the rect's bottom row, so a rect that exactly matched the drawn glyph would
    /// drop its own last row (this is what made every glyph render 1 px low
    /// before the 2026-08-12 master shift). Padding the rect by that one row
    /// makes the sprite cover cell rows 0..10 — the ten drawn rows plus one
    /// blank row — with the pivot at 5/11, landing the glyph's bottom 2 px below
    /// it: exactly vanilla's value (vanilla: floor(9/2) - 2 = 2; ours: floor(11/2)
    /// - 3 = 2).</para>
    ///
    /// <para>All 114 previous codepoints are a strict subset of the 331 shipped
    /// here, so nothing CK renders today loses its glyph.</para>
    ///
    /// <para>Kerning: rebuilding <c>glyphData</c> also drops vanilla's
    /// <c>kerning</c> byte arrays, so text renders wider without a
    /// replacement. <see cref="ApplyKerning"/> loads a generated
    /// <c>Cells x Cells</c> matrix (from ink-column geometry, calibrated
    /// against vanilla's own table to 97.66%) and then overwrites every pair
    /// vanilla actually had with vanilla's real values -- captured from
    /// <c>thinTiny</c> before this patch mutates it, since <c>InitCodePoints()</c>
    /// clears <c>codePoints</c> and a live reference would read back empty.</para>
    /// </summary>
    [HarmonyPatch(typeof(TextManager), "Init2")]
    internal static class ThinTinyFontPatch
    {
        private const string AssetPath = "Assets/CompleteTinyFont/Art/thinTiny_full.png";
        private const string KerningAssetPath = "Assets/CompleteTinyFont/Art/thinTiny_kerning.bytes";

        private const int Cols = 32;
        private const int CellW = 8;
        private const int CellH = 12;
        private const int BoxH = 10; // drawn glyph rows inside a cell (rows 0..9 since the 2026-08-12 master shift)
        private const int RectH = 12; // BoxH + 2: one row CK discards (rect2 = y+1, h-1), one to put the pivot on vanilla's baseline
        private const int AtlasH = 144;
        private const int Cells = 384; // == PugFont.latinCharset.Length

        /// <summary>
        /// Advance width per atlas cell, '0'..'8'; '0' marks an empty cell.
        /// Generated by utils/pixaki_to_glyphs.py — do not hand-edit.
        /// </summary>
        private const string Widths =
            "55777777000446400000000000000000"
            + "72353352225323133333333333222323"
            + "53333333313335333333333333323233"
            + "43333323312325333332233333332355"
            + "33343333333323343334343333444330"
            + "33343333333323343334343333556600"
            + "23313434432333333433333333333330"
            + "33333435533432440000000000000000"
            + "53345353344345333333335335453634"
            + "53345353344345333333335335453634"
            + "33113343333553333333333335444330"
            + "22543322224433553333323333000000";

        public static bool Applied { get; private set; }

        [HarmonyPostfix]
        private static void Postfix()
        {
            TryApply();
        }

        /// <summary>Idempotent; applies as soon as font and bundle are both ready.</summary>
        public static void TryApply()
        {
            if (Applied)
                return;
            try
            {
                var tm = Manager.text;
                var f = tm != null ? tm.thinTiny : null;
                if (f == null)
                    return;

                var bundle = CompleteTinyFontMod.AssetBundle;
                if (bundle == null)
                    return;

                var sheet = bundle.LoadAsset<Sprite>(AssetPath);
                if (sheet == null)
                {
                    Debug.LogWarning($"[{CompleteTinyFontMod.Name}] atlas sprite not found in bundle: {AssetPath}");
                    return;
                }

                // Capture vanilla's own data before mutating anything below.
                // A reference to f.glyphData survives the reassignment further
                // down (the old array's GlyphData objects are untouched), but
                // f.codePoints does not: InitCodePoints() clears it in place,
                // so only a real copy still holds vanilla's char -> index map.
                var oldGlyphs = f.glyphData;
                var oldCodePoints = new Dictionary<char, int>(f.codePoints);

                f.texture = sheet.texture;
                f._customCharset = null; // -> PugFont.latinCharset, the order the atlas is drawn in
                f.charDims = new Vector2Int(CellW, BoxH); // layout metric: unchanged from vanilla
                f.glyphData = BuildGlyphData(Math.Min(f.charset.Length, Cells));
                f.InitCodePoints(); // CK builds codePoints + volatileSprites itself
                Applied = true;

                ApplyKerning(f, bundle, oldGlyphs, oldCodePoints, out int rowsFilled, out int vanillaPairs);

                Debug.Log(
                    $"[{CompleteTinyFontMod.Name}] thinTiny replaced: {f.codePoints.Count} codepoints from a {f.texture.width}x{f.texture.height} atlas; "
                        + $"kerning {rowsFilled} rows, {vanillaPairs} vanilla pairs restored"
                );
            }
            catch (Exception ex)
            {
                // Sandbox-safe: never touch ex.GetType().Name here.
                Debug.LogError($"[{CompleteTinyFontMod.Name}] font replacement threw: {ex.Message}");
            }
        }

        /// <summary>
        /// Loads the generated kerning matrix and applies it to every painted
        /// glyph, then overwrites the pairs vanilla actually had with
        /// vanilla's own values (its 114-codepoint table beats the generated
        /// rule's 97.66% approximation for the characters both fonts share).
        /// Best-effort: a missing or malformed asset logs a warning and
        /// leaves every glyph's <c>kerning</c> at its <see cref="BuildGlyphData"/>
        /// default (null, i.e. no correction) rather than throwing.
        /// </summary>
        private static void ApplyKerning(
            PugFont f,
            AssetBundle bundle,
            PugFont.GlyphData[] oldGlyphs,
            Dictionary<char, int> oldCodePoints,
            out int rowsFilled,
            out int vanillaPairsRestored
        )
        {
            rowsFilled = 0;
            vanillaPairsRestored = 0;

            var kerningAsset = bundle.LoadAsset<TextAsset>(KerningAssetPath);
            if (kerningAsset == null)
            {
                Debug.LogWarning($"[{CompleteTinyFontMod.Name}] kerning matrix not found in bundle: {KerningAssetPath}");
                return;
            }
            byte[] matrix = kerningAsset.bytes;
            if (matrix == null || matrix.Length != Cells * Cells)
            {
                Debug.LogWarning(
                    $"[{CompleteTinyFontMod.Name}] kerning matrix has unexpected length: {matrix?.Length ?? 0}, expected {Cells * Cells}"
                );
                return;
            }

            for (int i = 0; i < f.glyphData.Length; i++)
            {
                if (i >= Widths.Length || Widths[i] == '0')
                    continue;
                var row = new byte[Cells];
                Array.Copy(matrix, i * Cells, row, 0, Cells);
                f.glyphData[i].kerning = row;
                rowsFilled++;
            }

            foreach (var cEntry in oldCodePoints)
            {
                if (!f.codePoints.TryGetValue(cEntry.Key, out int newA))
                    continue;
                int oldA = cEntry.Value;
                if (oldA < 0 || oldA >= oldGlyphs.Length)
                    continue;
                byte[] oldRow = oldGlyphs[oldA].kerning;
                if (oldRow == null)
                    continue;
                byte[] newRow = f.glyphData[newA].kerning;
                if (newRow == null)
                    continue;

                foreach (var dEntry in oldCodePoints)
                {
                    if (!f.codePoints.TryGetValue(dEntry.Key, out int newB))
                        continue;
                    int oldB = dEntry.Value;
                    if (oldB < 0 || oldB >= oldRow.Length)
                        continue;
                    if (newB < 0 || newB >= newRow.Length)
                        continue;

                    newRow[newB] = oldRow[oldB];
                    vanillaPairsRestored++;
                }
            }
        }

        private static PugFont.GlyphData[] BuildGlyphData(int count)
        {
            var gd = new PugFont.GlyphData[count];
            for (int i = 0; i < count; i++)
            {
                var g = new PugFont.GlyphData();
                int w = i < Widths.Length ? Widths[i] - '0' : 0;
                if (w > 0)
                {
                    int col = i % Cols;
                    int row = i / Cols;
                    // y flipped to Unity's bottom-left origin. The rect is one
                    // row taller than the drawn glyph (RectH = BoxH + 2, not
                    // BoxH) — see the class doc comment for why.
                    g.rect = new RectInt(col * CellW, AtlasH - (row * CellH + RectH), w, RectH);
                }
                // An empty cell keeps its default zero-size rect, which
                // InitCodePoints skips — that is how the charset's spaces and
                // unpainted cells stay unmapped.
                gd[i] = g;
            }
            return gd;
        }
    }
}
